---
title: "à propos"
---


<span class="contours-word">contours</span> est un espace de publication consacré aux sciences sociales, à la cartographie et à la dataviz en Nouvelle-Calédonie.

L'objectif est de proposer des analyses accessibles, documentées et reproductibles sur les dynamiques territoriales calédoniennes : populations, élections, mobilités, alimentation, infrastructures, environnement, inégalités spatiales et politiques publiques.

## Auteur

Le blog est présenté par <span class="contours-word">Jonas Brouillon</span>, ingénieur d'études en sciences sociales à l'IAC depuis 2021, et responsable du Centre de Recherche Nord à Pouembout depuis 2026.

Ce blog et ces travaux sont une initiative purement personnelle, ayant pour but de rendre accessible des analyses scientifiques au grand public sur des sujets d'interets pour la Nouvelle-Calédonie. Le temps long de la publication scientifique n'est parfois pas compatible avec la volonté de partager des analyses sur des sujets d'actualité, d'où le choix de ce format de blog. Les analyses publiées ici n'engagent que leur(s) auteur(s) et restent des analyses scientifiques, avec leurs limites et incertitudes, et ne sont pas des prises de position politiques. Les résulats doivent être considérés comme des éléments d'information et de réflexion, et non comme des recommandations ou des prescriptions d'action. Les analyses publiées ici sont basées sur des données publiques, des méthodes scientifiques reconnues et une démarche de transparence et de reproductibilité. Les sources de données, les codes utilisés pour les analyses et les visualisations seront partagés dans la mesure du possible pour permettre à chacun de vérifier, reproduire ou approfondir les analyses présentées.

## Ligne éditoriale

Les articles peuvent prendre plusieurs formes :

-   analyses courtes appuyées sur des cartes ou graphiques ;
-   notes méthodologiques en R, Quarto ou QGIS ;
-   explorations de données publiques ;
-   visualisations commentées ;
-   dossiers territoriaux sur la Nouvelle-Calédonie et le Pacifique.